---
title: "Statistics 433: Faculty Table"
author: "Marissa Schladweiler"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
# The UW-Madison Faculty information used for this project can be found at the URL below
# The rvest R package allows you to easily scrape data from webpages (similar to BeautifulSoup in Python)
library(rvest)

# read_html automatically inputs the information from this URL into R
faculty_page = read_html("https://guide.wisc.edu/faculty/")
```

To extract only the faculty information we want (name, position, department, degree info), it was necessary to find the appropriate tag that encodes this desired information. This was done by using the Developer Tools in the Chrome web browser settings where it was found that each new person was encoded in paragraph nodes represented by "p"
```{r}
# html_nodes() finds all nodes that match the tag (in our case, "p") and puts each of those elements in a list
faculty_nodes = faculty_page %>% html_nodes("p")

# Now we have a list of each faculty members' information (each row is a new person)
# However, there is a <br> between each piece of information for each person, so xml_find_all and xml_add_sibling finds these and replaces them with ";" for easier separation later
xml_find_all(faculty_nodes, ".//br") %>% xml_add_sibling("p", ";")

# Now we use html_text() to get the raw text of faculty information (now separated by semicolons), and remove non-faculty information (first two rows and last row)
faculty_nodes = html_text(faculty_nodes)[c(-1, -2, -3991)]
```


```{r, comment=NA}
# This loops through each person in the list, extracts their name, position, department, and degree info and 
# binds them to data frame where each person is a new row
library(stringr)
faculty_data = data.frame()
for(i in 1:length(faculty_nodes)){
  cols = str_split(faculty_nodes[i], ";")[[1]][1:4]
  faculty_data = rbind(faculty_data, cols, stringsAsFactors=FALSE)
}
```

```{r warning=FALSE}
# This changes the column names and displays the data frame
library(kableExtra)
colnames(faculty_data) = c("Name", "Position", "Department", "Degree Info")
kbl(faculty_data[1:20,])
```

